
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 105
#define YY_END_OF_BUFFER 106
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[525] =
    {   0,
        0,    0,   12,   12,   13,   13,   18,   18,   21,   21,
       24,   24,   27,   27,   30,   30,   33,   33,   36,   36,
       41,   41,   46,   46,    0,    0,    0,    0,  106,  105,
      104,  102,  102,  105,  105,   12,   13,   18,   21,   24,
       27,   30,   33,   36,   41,   46,  105,  105,   46,  103,
      105,  102,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   12,   13,   18,   21,   24,
       27,   30,   33,   36,   41,   46,    0,    0,    0,    0,
       46,  103,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   46,    0,   29,    0,    0,    0,    0,  101,
        0,    0,    0,    0,    0,    7,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   40,    0,    0,    0,
        0,    0,   26,   28,    0,    0,    0,  100,    0,    0,

        0,    0,    0,    3,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   39,    5,    6,
        0,    0,    0,    0,    0,    4,   25,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   46,    0,   29,    0,
       32,   43,   69,  101,    0,    0,    0,    0,   93,    7,
        0,    0,    0,    0,    0,   87,   75,    0,   91,    0,
       35,   40,   17,    0,    0,    0,    0,   26,   28,    0,
       42,   68,  100,    0,    0,    0,    0,   92,    3,    0,
        0,    0,    0,   86,    0,   74,    0,   90,    0,   88,

       31,    0,   34,   39,    5,    6,   16,    0,    0,    0,
        0,    4,   25,    0,    0,   55,    0,    0,    0,    0,
        0,   51,    0,    0,    0,    0,   54,    0,    0,    0,
        0,   50,    0,    0,   46,   47,   89,    0,   32,   43,
       69,   71,    0,   73,   83,   93,    0,   85,   38,   81,
       23,   87,   75,    0,   91,    0,   35,   17,    0,    0,
        0,    9,    0,   42,   68,   70,    0,   72,   82,   92,
        0,   84,   37,   80,   86,   44,   74,    0,   90,    0,
       88,   31,   22,   34,   16,    0,    0,    0,    8,    0,
       59,   55,   49,    0,    0,    0,   45,   51,   53,   63,

        0,   58,   54,   48,    0,    0,    0,   50,   52,   62,
       89,   15,   71,    0,   73,   83,   95,   85,   38,   81,
       23,    0,    0,   99,   20,    2,    0,    9,   14,   70,
        0,   72,   82,   94,   84,   37,   80,   44,    0,    0,
       98,   22,   19,    1,    0,    8,    0,   59,   49,    0,
        0,   57,   45,   53,   63,    0,   58,   48,    0,    0,
       56,   52,   62,   15,    0,   95,   77,    0,   99,   20,
        2,    0,   14,    0,   94,   76,    0,   98,   19,    1,
        0,    0,   67,   65,   57,    0,   66,   64,   56,   97,
       77,    0,   11,   96,   76,    0,   10,   61,   67,   65,

       60,   66,   64,   97,    0,   11,   96,    0,   10,   61,
       60,    0,    0,    0,    0,    0,    0,    0,    0,   79,
       78,   79,   78,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    5,    1,    5,
        5,    5,    5,    5,    7,    8,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    5,    5,    1,
        1,    1,    5,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       21,   28,   29,   30,   31,   21,   21,   32,   33,   21,
       34,   35,   34,   34,   36,   34,   21,   21,   21,   21,

       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   37,   21,
       21,   21,    6,    1,    6,    1,    1,    1,    1,    5,
        5,    1,    1,    1,    1,    5,    1,    1,    1,    5,
        5,    1,    1,    1,    1,    1,    1,    5,    5,    1,
        1,    1,    5,    1,    1,    1,    1,    1,    1,    5,
        5,    1,    5,    1,    1,    1,    5,    5,    5,    1,
        1,    5,    5,    1,    1,    1,    1,    5,    5,    5,
        5,    1,    1,    1,    5,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[38] =
    {   0,
        1,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       10,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,   11,   11,   12,    3
    } ;

static yyconst flex_int16_t yy_base[554] =
    {   0,
        0,   35,   70,  105,  140,  175,  210,  221,  232,  243,
      254,  263,  272,  283,  294,  305,  316,  352,  388,  424,
      460,  496,  532,  569,    0,    0,  606,  641,  794, 1093,
     1093,    0,    0,  665,  685,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    1,  756,    0,
      777,    0,    1,  778,  705,  764,  772,    0,  771,  755,
      765,  755,    2,  724,  756,  768,  755,  749,  757,  746,
        1,  753,  737,    2,  739,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  743,  746,  764,  745,
      727,    0,  736,  744,  729,  728,    2,    1,   28,  736,

       21,  722,  718,  729,  723,  728,  702,   26,  720,  702,
      693,  700,  706,  685,  698,  679,  683,  687,  673,    4,
       24,   37,  686,   31,  664,  661,  673,  668,  655,  672,
       27,  671,  667,  649,  666,  645,  640,   35,  648,  656,
      643,  656,  638,  653,  643,  651,  638,  643,  636,   29,
      649,  644,  631,  628,  643,  630,  635,  628,   36,  637,
      623,  619,  640,  632,  642,  626,  628,  610,  613,  633,
      621,  608,  622,  604,  614,  627,  618,  613,  595,  598,
      606,  601,  610,   40,  610,  592,  617,  604,  603,  592,
      586,  591,  609,  608,  592,  581,  584,  601,  587,  574,

      588,  570,  580,  593,  584,  579,  561,  564,  568,  563,
      576,   50,  576,  572,  571,  566,  555,  580,  579,  578,
      565,  563,  551,  546,  551,  569,  564,  537,  541,  533,
      536,  538,   66,  532,  542,  542,  534,  528,  532,  524,
      527,  529,   68,  534,  534,  526,   78,  532,  543,  520,
      541,  540,  538,  536,  506,  507,  509,  515,  524,  523,
      499,  501,  495,  493,  499,  517,  516,  490,  514,  494,
      512,  511,  510,  488,  484,  491,  494,  505,  504,  474,
      489,  488,  487,  457,  459,  461,  473,  482,  481,  457,
      459,  453,  451,  476,  467,  474,  448,  472,  452,  470,

      469,  449,  460,  453,  452,  451,  450,  428,  424,  431,
      434,  445,  444,  421,  431,  441,  414,  423,  419,  413,
      428,  435,  421,  421,  410,  413,  417,  390,  399,  395,
      389,  412,  398,  398,   84,    0,  409,  384,  407,  406,
      405,  404,  387,  402,  401,  400,  384,  398,  397,  396,
      388,  381,  380,   44,  379,  366,  377,  376,  349,  348,
      347,  372,  347,  370,  369,  368,  351,  366,  365,  364,
      348,  362,  361,  360,  358,  352,  345,   46,  344,  331,
      342,  341,  340,  339,  338,  311,  310,  309,  334,  312,
      332,  331,  330,  308,  312,  307,  326,  325,  324,  322,

      295,  311,  305,  300,  273,  273,  263,  278,  272,  267,
      266,  263,  258,  235,  254,  249,  243,  238,  232,  227,
      221,  206,  201,  204,  203,  202,  182,  200,  199,  198,
      175,  196,  195,  194,  193,  192,  191,  190,  179,  179,
      187,  186,  185,  184,  164,  181,  150,  178,  176,  163,
      159,  168,  167,  166,  165,  135,  163,  162,  149,  150,
      159,  158,  157,  156,  134,  154,  153,  127,  151,  150,
      149,  136,  146,  123,  143,  141,  115,  134,  133,  132,
      119,  110,  129,  128,  127,  106,  125,  124,  123,  122,
      121,  108,  119,  118,  117,  104,  115,  114,  113,  111,

      109,  108,  106,  105,   89,   98,   97,   86,   95,   94,
       93,   66,   65,   72,   70,   60,   42,   42,    4,   19,
        6,    4,    3, 1093,  796,  808,  820,  832,  844,  856,
      868,  880,  892,  904,  916,  928,  940,  952,  962,  972,
      982,  992, 1002, 1012, 1022, 1032, 1042,    3,    2, 1049,
     1060, 1070, 1080
    } ;

static yyconst flex_int16_t yy_def[554] =
    {   0,
      525,  525,  526,  526,  527,  527,  528,  528,  529,  529,
      530,  530,  531,  531,  532,  532,  533,  533,  534,  534,
      535,  535,  536,  536,  537,  537,  538,  538,  524,  524,
      524,  539,  539,  524,  524,  540,  541,  542,  543,  544,
      545,  546,  547,  548,  549,  550,  524,  524,  550,  551,
      524,  539,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  540,  541,  542,  543,  544,
      545,  546,  547,  548,  549,  550,  524,  524,  524,  524,
      550,  551,  524,  524,  524,  524,  524,  524,  524,  524,

      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  550,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,

      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  552,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,

      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  552,  553,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,

      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,

      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,    0,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524
    } ;

static yyconst flex_int16_t yy_nxt[1131] =
    {   0,
       30,   31,   31,   32,   85,   84,  523,  522,   34,  523,
       30,  112,  139,   89,  168,   87,  196,   94,  118,  113,
      140,  143,  522,  169,  170,  197,  171,  144,  521,   88,
       90,   95,  119,   30,   35,   30,   31,   31,   32,  172,
      175,  183,  211,   34,  176,   30,  173,  198,  200,  199,
      203,  219,  268,  232,  204,  201,  184,  212,  233,  422,
      242,  439,  297,  269,  220,  243,  520,  519,   30,   35,
       30,   30,   30,  298,  423,   30,  440,  319,   30,  330,
       30,  320,   86,  331,   86,  518,  336,   86,   86,  517,
       86,  516,  336,   86,  515,  514,  511,  510,  509,  513,

      507,  506,  512,   30,   30,   30,   30,   30,  504,  503,
       30,  502,  511,   30,  500,   30,  499,  510,  509,  508,
      495,  507,  506,  505,  491,  504,  489,  503,  502,  501,
      485,  500,  499,  498,  497,  480,  479,  478,   30,   30,
       30,   30,   30,  496,  495,   30,  475,  494,   30,  473,
       30,  493,  471,  470,  469,  492,  491,  466,  490,  464,
      463,  462,  489,  488,  487,  458,  457,  486,  455,  454,
      453,  485,  484,   30,   30,   30,   30,   30,  483,  449,
       30,  448,  482,   30,  446,   30,  481,  480,  479,  442,
      478,  477,  476,  438,  437,  436,  435,  475,  433,  432,

      474,  430,  473,  428,  472,  471,  470,  469,   30,   30,
       30,   30,   30,  468,   30,   30,   30,   30,   30,  467,
       30,   30,   30,   30,  421,   30,   30,   30,   30,   30,
      420,   30,   30,   30,   30,  419,   30,   30,   30,   30,
       30,  418,   30,   30,   30,   30,  466,   30,   30,   30,
       30,   30,  416,   30,   30,   30,   30,  415,   30,   30,
      465,  413,   30,   30,   30,   30,  464,   30,   30,  411,
      463,   30,   30,   30,   30,  462,   30,   30,   30,   30,
       30,  408,   30,   30,   30,   30,  461,   30,   30,   30,
       30,   30,  460,   30,   30,   30,   30,  459,   30,   30,

       30,   30,   30,  458,   30,   30,   30,   30,  403,   30,
       30,   30,   30,   30,  457,   30,   30,   30,   30,  456,
       30,   30,   30,   30,   30,  455,   30,  454,  398,  453,
      452,  451,  450,  449,  392,  448,  447,  446,  445,  444,
      443,  385,  384,  442,  382,  381,  441,  379,  377,   30,
       30,   30,   30,   30,   30,  438,   30,   30,   30,   30,
       30,  375,   30,  437,  436,  435,  434,  370,  433,  432,
      431,  430,  365,  364,  429,  428,  427,  426,  425,  358,
      357,  424,  355,  353,  352,   30,   30,   30,   30,   30,
       30,  421,   30,   30,   30,   30,   30,   30,   30,  420,

      419,  418,  417,  346,  416,  415,  414,  413,  341,  340,
      339,  412,  411,  410,  409,  408,  407,  406,  405,  404,
      403,   30,   30,   30,   30,   30,   30,  402,   30,   30,
       30,   30,   30,   30,   30,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  313,  312,  389,
      388,  387,  386,  385,  306,  305,  304,   30,   30,   30,
       30,   30,   30,  384,   30,   30,   30,   30,   30,   30,
       30,  383,  382,  381,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  289,  370,  369,  368,  367,  366,
      283,  365,  364,   30,   30,   30,   30,   30,   30,  363,

       30,   30,   30,   30,   30,   30,   30,  279,  278,  362,
      361,  360,  359,  358,  272,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  260,  346,  345,   30,
       30,   30,   30,   30,   30,  344,  343,   30,  342,  254,
       47,  341,   30,  340,  339,  338,  249,  337,  334,  333,
      332,  329,  328,  327,  326,  325,  324,  323,  322,  321,
      318,  317,  316,  315,  314,   30,   48,  313,   49,   30,
       30,   30,  312,  311,   30,  310,  309,   47,  308,   30,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,

      285,  284,   30,   48,  283,   49,   30,   30,  282,  281,
      280,  279,  278,  277,   51,  276,   30,  275,  274,  273,
      272,  271,  270,  267,  266,  265,  264,  263,  262,  261,
      260,  259,  258,  257,  256,  255,  254,  253,  252,   30,
       30,   30,   30,  251,  250,  249,  248,  247,  246,   51,
      245,   30,  244,  241,  240,  239,  238,  237,  236,  235,
      234,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  218,  217,   30,   30,   53,  216,  215,   54,
       55,  214,  213,  210,   56,  209,   57,  208,  207,   58,
      206,  205,   59,   60,   61,   62,   63,   64,   65,   66,

       67,  202,  195,  194,   68,  193,   69,   70,  192,   71,
      191,  190,   72,   73,   74,   75,   97,   98,   99,  100,
      189,  101,  102,  188,  103,  187,  104,  105,  106,  107,
      186,  185,  182,  108,  109,  120,  121,  122,  123,  181,
      124,  125,  180,  126,  179,  127,  128,  178,  129,  177,
      130,  174,  131,  132,  146,  147,  148,  167,  166,  149,
      165,  164,  150,  163,  162,  154,  145,  142,  141,  151,
      152,  138,  137,  136,  153,  155,  156,  157,  135,  134,
      158,  133,  117,  159,  116,  115,  114,  111,  110,   96,
       93,  160,   91,  524,  524,  161,   33,   33,   33,   33,

       33,   33,   33,   33,   33,   33,   33,   33,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   43,   43,   43,   43,   43,   43,   43,   43,

       43,   43,   43,   43,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   52,   52,   52,   52,   52,  524,
       52,  524,  524,   52,   76,   76,  524,   76,   76,  524,
       76,  524,  524,   76,   77,   77,  524,   77,   77,  524,
       77,  524,  524,   77,   78,  524,  524,  524,  524,  524,

       78,  524,   78,   78,   79,  524,  524,  524,  524,  524,
       79,  524,   79,   79,   80,  524,  524,   80,   80,  524,
       80,   80,   80,   80,   81,  524,  524,  524,  524,  524,
       81,  524,   81,   81,   82,  524,  524,  524,  524,  524,
       82,  524,   82,   82,   83,  524,  524,  524,  524,  524,
       83,   86,   86,  524,   86,   86,  524,   86,  524,  524,
       86,   92,   92,   92,   92,   92,   92,  524,   92,  524,
      524,   92,  335,  335,  524,  335,  335,  335,  335,  524,
      524,  335,  336,  524,  524,  524,  336,  336,  524,  524,
      524,  336,   29,  524,  524,  524,  524,  524,  524,  524,

      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524
    } ;

static yyconst flex_int16_t yy_chk[1131] =
    {   0,
        1,    1,    1,    1,  549,  548,  523,  522,    1,  521,
        1,   58,   71,   48,   97,   47,  120,   53,   63,   58,
       71,   74,  520,   97,   98,  120,   98,   74,  519,   47,
       48,   53,   63,    1,    1,    2,    2,    2,    2,   99,
      101,  108,  131,    2,  101,    2,   99,  121,  122,  121,
      124,  138,  184,  150,  124,  122,  108,  131,  150,  354,
      159,  378,  212,  184,  138,  159,  518,  517,    2,    2,
        3,    3,    3,  212,  354,    3,  378,  233,    3,  243,
        3,  233,  247,  243,  247,  516,  247,  247,  335,  515,
      335,  514,  335,  335,  513,  512,  511,  510,  509,  508,

      507,  506,  505,    3,    3,    4,    4,    4,  504,  503,
        4,  502,  501,    4,  500,    4,  499,  498,  497,  496,
      495,  494,  493,  492,  491,  490,  489,  488,  487,  486,
      485,  484,  483,  482,  481,  480,  479,  478,    4,    4,
        5,    5,    5,  477,  476,    5,  475,  474,    5,  473,
        5,  472,  471,  470,  469,  468,  467,  466,  465,  464,
      463,  462,  461,  460,  459,  458,  457,  456,  455,  454,
      453,  452,  451,    5,    5,    6,    6,    6,  450,  449,
        6,  448,  447,    6,  446,    6,  445,  444,  443,  442,
      441,  440,  439,  438,  437,  436,  435,  434,  433,  432,

      431,  430,  429,  428,  427,  426,  425,  424,    6,    6,
        7,    7,    7,  423,    7,    7,    7,    7,    7,  422,
        7,    8,    8,    8,  421,    8,    8,    8,    8,    8,
      420,    8,    9,    9,    9,  419,    9,    9,    9,    9,
        9,  418,    9,   10,   10,   10,  417,   10,   10,   10,
       10,   10,  416,   10,   11,   11,   11,  415,   11,   11,
      414,  413,   11,   12,   12,   12,  412,   12,   12,  411,
      410,   12,   13,   13,   13,  409,   13,   13,   13,   13,
       13,  408,   13,   14,   14,   14,  407,   14,   14,   14,
       14,   14,  406,   14,   15,   15,   15,  405,   15,   15,

       15,   15,   15,  404,   15,   16,   16,   16,  403,   16,
       16,   16,   16,   16,  402,   16,   17,   17,   17,  401,
       17,   17,   17,   17,   17,  400,   17,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  377,   17,
       17,   17,   18,   18,   18,  376,   18,   18,   18,   18,
       18,  375,   18,  374,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  353,  352,   18,   18,   18,   19,   19,
       19,  351,   19,   19,   19,   19,   19,   19,   19,  350,

      349,  348,  347,  346,  345,  344,  343,  342,  341,  340,
      339,  338,  337,  334,  333,  332,  331,  330,  329,  328,
      327,   19,   19,   19,   20,   20,   20,  326,   20,   20,
       20,   20,   20,   20,   20,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  312,  311,
      310,  309,  308,  307,  306,  305,  304,   20,   20,   20,
       21,   21,   21,  303,   21,   21,   21,   21,   21,   21,
       21,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,   21,   21,   21,   22,   22,   22,  280,

       22,   22,   22,   22,   22,   22,   22,  279,  278,  277,
      276,  275,  274,  273,  272,  271,  270,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,   22,
       22,   22,   23,   23,   23,  257,  256,   23,  255,  254,
       23,  253,   23,  252,  251,  250,  249,  248,  246,  245,
      244,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      232,  231,  230,  229,  228,   23,   23,  227,   23,   24,
       24,   24,  226,  225,   24,  224,  223,   24,  222,   24,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,

      200,  199,   24,   24,  198,   24,   27,   27,  197,  196,
      195,  194,  193,  192,   27,  191,   27,  190,  189,  188,
      187,  186,  185,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,   27,
       27,   28,   28,  167,  166,  165,  164,  163,  162,   28,
      161,   28,  160,  158,  157,  156,  155,  154,  153,  152,
      151,  149,  148,  147,  146,  145,  144,  143,  142,  141,
      140,  139,  137,  136,   28,   28,   34,  135,  134,   34,
       34,  133,  132,  130,   34,  129,   34,  128,  127,   34,
      126,  125,   34,   34,   34,   34,   35,   35,   35,   35,

       35,  123,  119,  118,   35,  117,   35,   35,  116,   35,
      115,  114,   35,   35,   35,   35,   55,   55,   55,   55,
      113,   55,   55,  112,   55,  111,   55,   55,   55,   55,
      110,  109,  107,   55,   55,   64,   64,   64,   64,  106,
       64,   64,  105,   64,  104,   64,   64,  103,   64,  102,
       64,  100,   64,   64,   87,   87,   87,   96,   95,   87,
       94,   93,   87,   91,   90,   88,   75,   73,   72,   87,
       87,   70,   69,   68,   87,   89,   89,   89,   67,   66,
       89,   65,   62,   89,   61,   60,   59,   57,   56,   54,
       51,   89,   49,   29,    0,   89,  525,  525,  525,  525,

      525,  525,  525,  525,  525,  525,  525,  525,  526,  526,
      526,  526,  526,  526,  526,  526,  526,  526,  526,  526,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  529,  529,  529,  529,  529,  529,
      529,  529,  529,  529,  529,  529,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  531,  531,
      531,  531,  531,  531,  531,  531,  531,  531,  531,  531,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  533,  533,  533,  533,  533,  533,  533,  533,

      533,  533,  533,  533,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  539,  539,  539,  539,  539,    0,
      539,    0,    0,  539,  540,  540,    0,  540,  540,    0,
      540,    0,    0,  540,  541,  541,    0,  541,  541,    0,
      541,    0,    0,  541,  542,    0,    0,    0,    0,    0,

      542,    0,  542,  542,  543,    0,    0,    0,    0,    0,
      543,    0,  543,  543,  544,    0,    0,  544,  544,    0,
      544,  544,  544,  544,  545,    0,    0,    0,    0,    0,
      545,    0,  545,  545,  546,    0,    0,    0,    0,    0,
      546,    0,  546,  546,  547,    0,    0,    0,    0,    0,
      547,  550,  550,    0,  550,  550,    0,  550,    0,    0,
      550,  551,  551,  551,  551,  551,  551,    0,  551,    0,
        0,  551,  552,  552,    0,  552,  552,  552,  552,    0,
        0,  552,  553,    0,    0,    0,  553,  553,    0,    0,
        0,  553,  524,  524,  524,  524,  524,  524,  524,  524,

      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  524,  524,  524,  524
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[106] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "report.l"
#line 2 "report.l"
#include "report2007.h"
#include "y.tab.h"
#include <string.h>
#include <stdlib.h>

#line 906 "lex.yy.c"

#define INITIAL 0
#define title 1
#define subtitle 2
#define name 3
#define ident 4
#define email 5
#define url 6
#define aff 7
#define date 8
#define inst 9
#define key 10
#define para 11
#define akn 12
#define code 13

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 10 "report.l"


#line 1104 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 525 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1093 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 12 "report.l"
{return BREPORT;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 13 "report.l"
{return EREPORT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 14 "report.l"
{return BFM;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 15 "report.l"
{return TOC;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 16 "report.l"
{return LOF;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 17 "report.l"
{return LOT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 18 "report.l"
{return EFM;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 19 "report.l"
{BEGIN title; return BTITLE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 20 "report.l"
{return ETITLE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 21 "report.l"
{BEGIN subtitle; return BSUBTITLE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 22 "report.l"
{return ESUBTITLE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 23 "report.l"
{BEGIN 0;yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 24 "report.l"
{BEGIN 0;yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 25 "report.l"
{return BAUTHOR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 26 "report.l"
{return EAUTHOR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 27 "report.l"
{BEGIN name;return BNAME;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 28 "report.l"
{return ENAME;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 29 "report.l"
{BEGIN 0;yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 30 "report.l"
{BEGIN ident;return BIDENT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 31 "report.l"
{return EINDENT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 32 "report.l"
{BEGIN 0; yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 33 "report.l"
{BEGIN email;return BMAIL;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 34 "report.l"
{return EMAIL;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 35 "report.l"
{BEGIN 0; yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 36 "report.l"
{BEGIN url;return BURL;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 37 "report.l"
{return EURL;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 38 "report.l"
{BEGIN 0; yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 39 "report.l"
{BEGIN aff; return BAFF;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 40 "report.l"
{return EAFF;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 41 "report.l"
{BEGIN 0; yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 42 "report.l"
{BEGIN date; return BDATE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 43 "report.l"
{return EDATE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 44 "report.l"
{BEGIN 0;yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 45 "report.l"
{BEGIN inst; return BINST;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 46 "report.l"
{return EINST;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 47 "report.l"
{BEGIN 0; yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 48 "report.l"
{return BKEYS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 49 "report.l"
{return EKEYS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 50 "report.l"
{BEGIN key;return BKEY;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 51 "report.l"
{return EKEY;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 52 "report.l"
{BEGIN 0;yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 53 "report.l"
{return BABS;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 54 "report.l"
{return EABS;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 55 "report.l"
{BEGIN para;return BPARA;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 56 "report.l"
{BEGIN 0;return EPARA;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 57 "report.l"
{yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 58 "report.l"
{yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 59 "report.l"
{return BFOOT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 60 "report.l"
{return EFOOT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 61 "report.l"
{return BREF;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 62 "report.l"
{return EREF;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 63 "report.l"
{return BXREF;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 64 "report.l"
{return EXREF;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 65 "report.l"
{return BCIT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 66 "report.l"
{return ECIT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 67 "report.l"
{return BITERM;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 68 "report.l"
{return EITERM;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 69 "report.l"
{return BBLOD;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 70 "report.l"
{return EBOLD;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 71 "report.l"
{return BACRONYM;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 72 "report.l"
{return EACRONYM;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 73 "report.l"
{return BTITLE;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 74 "report.l"
{return ETITLE;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 75 "report.l"
{return BITALIC;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 76 "report.l"
{return EITALIC;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 77 "report.l"
{return BINLINE;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 78 "report.l"
{return EINLINE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 79 "report.l"
{return BAKN;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 80 "report.l"
{return EAKN;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 81 "report.l"
{return BBODY;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 82 "report.l"
{return EBODY;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 83 "report.l"
{return BCHAP;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 84 "report.l"
{return ECHAP;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 85 "report.l"
{return BSEC;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 86 "report.l"
{return ESEC;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 87 "report.l"
{return BSUBSEC;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 88 "report.l"
{return ESUBSEC;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 89 "report.l"
{return BSUBSUBSECTION;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 90 "report.l"
{return ESUBSUBSECTION;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 91 "report.l"
{return BLIST;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 92 "report.l"
{return ELIST;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 93 "report.l"
{return BDESC;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 94 "report.l"
{return EDESC;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 95 "report.l"
{return BITEM;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 96 "report.l"
{return EITEM;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 97 "report.l"
{return BNUM;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 98 "report.l"
{return ENUM;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 99 "report.l"
{BEGIN code;return BCODE;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 100 "report.l"
{BEGIN 0;return ECODE;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 101 "report.l"
{return BSUM;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 102 "report.l"
{return ESUM;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 103 "report.l"
{return BFIG;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 104 "report.l"
{return EFIG;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 105 "report.l"
{return BGRAPH;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 106 "report.l"
{return EGRAPH;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 107 "report.l"
{return BCAPTION;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 108 "report.l"
{return ECAPTION;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 109 "report.l"
{return BTABLE;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 110 "report.l"
{return ETABLE;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 111 "report.l"
{return BBM;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 112 "report.l"
{return EBM;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 113 "report.l"
{yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 114 "report.l"
{yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 104:
/* rule 104 can match eol */
YY_RULE_SETUP
#line 115 "report.l"
;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 116 "report.l"
ECHO;
	YY_BREAK
#line 1724 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(title):
case YY_STATE_EOF(subtitle):
case YY_STATE_EOF(name):
case YY_STATE_EOF(ident):
case YY_STATE_EOF(email):
case YY_STATE_EOF(url):
case YY_STATE_EOF(aff):
case YY_STATE_EOF(date):
case YY_STATE_EOF(inst):
case YY_STATE_EOF(key):
case YY_STATE_EOF(para):
case YY_STATE_EOF(akn):
case YY_STATE_EOF(code):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 525 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 525 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 524);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 116 "report.l"
