
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 109
#define YY_END_OF_BUFFER 110
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[541] =
    {   0,
        0,    0,   12,   12,   13,   13,   18,   18,   21,   21,
       24,   24,   27,   27,   30,   30,   33,   33,   36,   36,
       41,   41,   46,   46,    0,    0,    0,    0,  110,  109,
      108,  106,  106,  109,  109,   12,   13,   18,   21,   24,
       27,   30,   33,   36,   41,   46,  109,  109,   46,  107,
      109,  106,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   12,   13,   18,   21,   24,
       27,   30,   33,   36,   41,   46,    0,    0,    0,    0,
       46,  107,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   46,    0,   29,    0,    0,    0,
        0,  105,    0,    0,    0,    0,    0,    0,    7,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       40,    0,    0,    0,    0,    0,   26,   28,    0,    0,

        0,  104,    0,    0,    0,    0,    0,    0,    3,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   39,    5,    6,    0,    0,    0,    0,
        0,    4,   25,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   46,    0,   29,    0,   32,   43,   69,  105,
        0,    0,    0,    0,    0,   93,    7,    0,    0,    0,
        0,    0,   87,  101,   75,    0,   91,    0,   35,   40,
       17,    0,    0,    0,    0,   26,   28,    0,   42,   68,
      104,    0,    0,    0,    0,    0,   92,    3,    0,    0,

        0,    0,   86,    0,  100,   74,    0,   90,    0,   88,
       31,    0,   34,   39,    5,    6,   16,    0,    0,    0,
        0,    4,   25,    0,    0,   55,    0,    0,    0,    0,
        0,   51,    0,    0,    0,    0,   54,    0,    0,    0,
        0,   50,    0,    0,   46,   47,   89,    0,   32,   43,
       69,   71,    0,  103,   73,   83,   93,    0,   85,   38,
       81,   23,   87,  101,   75,    0,   91,    0,   35,   17,
        0,    0,    0,    9,    0,   42,   68,   70,    0,  102,
       72,   82,   92,    0,   84,   37,   80,   86,   44,  100,
       74,    0,   90,    0,   88,   31,   22,   34,   16,    0,

        0,    0,    8,    0,   59,   55,   49,    0,    0,    0,
       45,   51,   53,   63,    0,   58,   54,   48,    0,    0,
        0,   50,   52,   62,   89,   15,   71,    0,  103,   73,
       83,   95,   85,   38,   81,   23,    0,    0,   99,   20,
        2,    0,    9,   14,   70,    0,  102,   72,   82,   94,
       84,   37,   80,   44,    0,    0,   98,   22,   19,    1,
        0,    8,    0,   59,   49,    0,    0,   57,   45,   53,
       63,    0,   58,   48,    0,    0,   56,   52,   62,   15,
        0,   95,   77,    0,   99,   20,    2,    0,   14,    0,
       94,   76,    0,   98,   19,    1,    0,    0,   67,   65,

       57,    0,   66,   64,   56,   97,   77,    0,   11,   96,
       76,    0,   10,   61,   67,   65,   60,   66,   64,   97,
        0,   11,   96,    0,   10,   61,   60,    0,    0,    0,
        0,    0,    0,    0,    0,   79,   78,   79,   78,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    5,    1,    5,
        5,    5,    5,    5,    7,    8,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    5,    5,    1,
        1,    1,    5,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       21,   28,   29,   30,   31,   21,   32,   33,   34,   21,
       35,   36,   35,   35,   37,   35,   21,   21,   21,   21,

       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   38,   21,
       21,   21,    6,    1,    6,    1,    1,    1,    1,    5,
        5,    1,    1,    1,    1,    5,    1,    1,    1,    5,
        5,    1,    1,    1,    1,    1,    1,    5,    5,    1,
        1,    1,    5,    1,    1,    1,    1,    1,    1,    5,
        5,    1,    5,    1,    1,    1,    5,    5,    5,    1,
        1,    5,    5,    1,    1,    1,    1,    5,    5,    5,
        5,    1,    1,    1,    5,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[39] =
    {   0,
        1,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       10,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,   11,   11,   12,    3
    } ;

static yyconst flex_int16_t yy_base[570] =
    {   0,
        0,   36,   72,  108,  144,  180,  216,  227,  238,  249,
      260,  269,  278,  289,  300,  311,  322,  359,  396,  433,
      470,  507,  544,  582,    0,    0,  620,  656,  990, 1111,
     1111,    0,    0,  681,  701,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    1,  950,    0,
      799,    0,    1,  800,  721,  786,  794,    0,  792,  776,
      786,  777,    2,  740,  778,  791,  778,  775,  783,  771,
        1,  780,  760,    2,  762,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  759,  769,  781,  768,
      747,    0,  758,  766,  752,  751,    2,    1,   30,  764,

       24,  750,  747,  759,  754,  754,  733,  735,   10,  747,
      727,  714,  723,  727,  713,  724,  698,  704,  708,  692,
       21,   26,   39,  704,   33,  691,  688,  692,  687,  674,
      692,  676,   38,  688,  684,  668,  683,  665,  656,   46,
      665,  673,  660,  673,  655,  670,  660,  668,  655,  660,
      653,   31,  666,  661,  648,  645,  660,  647,  652,  645,
       34,  654,  641,  638,  658,  649,  659,  643,  645,  631,
      634,  650,  638,  625,  628,  638,  620,  630,  643,  634,
      629,  610,  614,  622,  617,  608,  625,   53,  625,  607,
      632,  619,  618,  607,  602,  607,  624,  623,  607,  596,

      599,  619,  604,  589,  592,  602,  584,  594,  607,  598,
      593,  574,  578,  582,  577,  572,  589,   55,  589,  585,
      584,  579,  568,  593,  592,  591,  578,  576,  564,  559,
      564,  582,  577,  550,  554,  546,  549,  551,   68,  545,
      555,  555,  547,  541,  545,  537,  540,  542,   70,  547,
      547,  539,   80,  545,  556,  533,  554,  553,  552,  550,
      518,  521,  526,  521,  527,  536,  535,  511,  513,  507,
      505,  511,  529,  528,  527,  501,  525,  505,  523,  522,
      521,  499,  495,  502,  505,  516,  515,  485,  500,  499,
      498,  467,  470,  476,  471,  483,  492,  491,  467,  469,

      463,  461,  486,  477,  484,  483,  457,  481,  461,  479,
      478,  451,  463,  462,  461,  460,  459,  437,  433,  440,
      443,  454,  453,  430,  440,  450,  423,  432,  428,  422,
      437,  444,  430,  430,  419,  422,  426,  399,  408,  404,
      398,  421,  407,  407,   86,    0,  418,  393,  416,  415,
      414,  413,  396,  411,  410,  409,  408,  392,  406,  405,
      404,  396,  389,  388,  387,   72,  386,  373,  384,  383,
      356,  355,  354,  379,  354,  377,  376,  375,  358,  373,
      372,  371,  370,  354,  368,  367,  365,  359,  352,  351,
      350,   81,  349,  336,  347,  346,  345,  344,  343,  316,

      315,  314,  339,  317,  337,  336,  335,  313,  317,  312,
      331,  330,  328,  322,  296,  311,  306,  300,  274,  273,
      264,  278,  273,  272,  269,  264,  263,  238,  255,  249,
      244,  238,  233,  227,  222,  216,  200,  200,  208,  207,
      206,  186,  204,  203,  202,  179,  200,  199,  198,  197,
      196,  195,  194,  193,  182,  182,  190,  189,  188,  186,
      165,  183,  151,  180,  174,  161,  162,  171,  170,  169,
      168,  137,  166,  165,  152,  153,  162,  161,  160,  159,
      137,  157,  156,  130,  154,  153,  152,  138,  148,  126,
      145,  144,  113,  137,  136,  135,  122,  113,  132,  131,

      130,  109,  128,  127,  126,  125,  124,  111,  122,  121,
      120,  107,  118,  117,  116,  114,  112,  111,  109,  102,
       91,  100,   98,   87,   96,   95,   94,   64,   62,   50,
       47,   39,   36,   35,    4,   13,    6,    4,    3, 1111,
      814,  826,  838,  850,  862,  874,  886,  898,  910,  922,
      934,  946,  958,  970,  980,  990, 1000, 1010, 1020, 1030,
     1040, 1050, 1060,    3,    2, 1067, 1078, 1088, 1098
    } ;

static yyconst flex_int16_t yy_def[570] =
    {   0,
      541,  541,  542,  542,  543,  543,  544,  544,  545,  545,
      546,  546,  547,  547,  548,  548,  549,  549,  550,  550,
      551,  551,  552,  552,  553,  553,  554,  554,  540,  540,
      540,  555,  555,  540,  540,  556,  557,  558,  559,  560,
      561,  562,  563,  564,  565,  566,  540,  540,  566,  567,
      540,  555,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  556,  557,  558,  559,  560,
      561,  562,  563,  564,  565,  566,  540,  540,  540,  540,
      566,  567,  540,  540,  540,  540,  540,  540,  540,  540,

      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  566,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,

      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  568,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,

      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  568,  569,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,

      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,

      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,    0,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540
    } ;

static yyconst flex_int16_t yy_nxt[1150] =
    {   0,
       30,   31,   31,   32,   85,   84,  539,  538,   34,  539,
       30,  113,  141,   89,  170,   87,  538,   94,  119,  114,
      142,  145,  540,  171,  172,  187,  173,  146,  537,   88,
       90,   95,  120,  200,   30,   35,   30,   31,   31,   32,
      188,  174,  201,  178,   34,  175,   30,  179,  176,  202,
      204,  203,  208,  217,  205,  238,  209,  206,  248,  536,
      239,  535,  225,  249,  534,  276,  533,  307,  218,  532,
       30,   35,   30,   30,   30,  226,  277,   30,  308,  329,
       30,  340,   30,  330,   86,  341,   86,  437,  346,   86,
       86,  531,   86,  530,  346,   86,  455,  527,  526,  525,

      529,  523,  438,  522,  528,  520,   30,   30,   30,   30,
       30,  456,  519,   30,  518,  527,   30,  516,   30,  515,
      526,  525,  524,  511,  523,  522,  521,  507,  520,  505,
      519,  518,  517,  501,  516,  515,  514,  513,  496,  495,
      494,  512,   30,   30,   30,   30,   30,  511,  491,   30,
      510,  489,   30,  509,   30,  487,  486,  485,  508,  507,
      482,  506,  480,  479,  478,  505,  504,  503,  474,  473,
      502,  471,  470,  469,  501,  500,  499,  465,   30,   30,
       30,   30,   30,  464,  498,   30,  462,  497,   30,  496,
       30,  495,  458,  494,  493,  492,  454,  453,  452,  451,

      491,  449,  448,  447,  490,  445,  489,  443,  488,  487,
      486,  485,  484,  483,   30,   30,   30,   30,   30,  436,
       30,   30,   30,   30,   30,  435,   30,   30,   30,   30,
      434,   30,   30,   30,   30,   30,  433,   30,   30,   30,
       30,  482,   30,   30,   30,   30,   30,  431,   30,   30,
       30,   30,  430,   30,   30,   30,   30,   30,  429,   30,
       30,   30,   30,  481,   30,   30,  427,  480,   30,   30,
       30,   30,  425,   30,   30,  479,  478,   30,   30,   30,
       30,  422,   30,   30,   30,   30,   30,  477,   30,   30,
       30,   30,  476,   30,   30,   30,   30,   30,  475,   30,

       30,   30,   30,  474,   30,   30,   30,   30,   30,  417,
       30,   30,   30,   30,  473,   30,   30,   30,   30,   30,
      472,   30,   30,   30,   30,  471,   30,   30,   30,   30,
       30,  470,   30,  412,  469,  468,  467,  466,  465,  406,
      464,  463,  462,  461,  460,  459,  399,  398,  458,  396,
      395,  457,  393,  391,  390,  454,   30,   30,   30,   30,
       30,   30,  388,   30,   30,   30,   30,   30,  453,   30,
      452,  451,  450,  383,  449,  448,  447,  446,  445,  377,
      376,  444,  443,  442,  441,  440,  370,  369,  439,  367,
      365,  364,  363,   30,   30,   30,   30,   30,   30,  436,

       30,   30,   30,   30,   30,   30,   30,  435,  434,  433,
      432,  357,  431,  430,  429,  428,  427,  351,  350,  349,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,
       30,   30,   30,   30,   30,   30,  416,   30,   30,   30,
       30,   30,   30,   30,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  406,  405,  404,  323,  322,  403,  402,
      401,  400,  399,  316,  315,  314,  398,   30,   30,   30,
       30,   30,   30,  397,   30,   30,   30,   30,   30,   30,
       30,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  298,  383,  382,  381,  380,  379,

      378,  291,  377,  376,   30,   30,   30,   30,   30,   30,
      375,   30,   30,   30,   30,   30,   30,   30,  287,  286,
      374,  373,  372,  371,  370,  280,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  267,  357,
      356,   30,   30,   30,   30,   30,   30,  355,  354,   30,
      353,  352,   47,  260,   30,  351,  350,  349,  348,  255,
      347,  344,  343,  342,  339,  338,  337,  336,  335,  334,
      333,  332,  331,  328,  327,  326,  325,  324,   30,   48,
      323,   49,   30,   30,   30,  322,  321,   30,  320,  319,
       47,  318,   30,  317,  316,  315,  314,  313,  312,  311,

      310,  309,  306,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  295,  294,  293,   30,   48,  292,   49,
       30,   30,  291,  290,  289,  288,  287,  286,   51,  285,
       30,  284,  283,  282,  281,  280,  279,  278,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,   30,   30,   30,   30,  259,  258,
      257,  256,  255,  254,   51,  253,   30,  252,  251,  250,
      247,  246,  245,  244,  243,  242,  241,  240,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  224,
       30,   30,   53,  223,  222,   54,   55,  221,  220,  219,

       56,  216,   57,  215,  214,   58,  213,  212,   59,   60,
       61,   62,   63,   64,   65,   66,   67,  211,  210,  207,
       68,  199,   69,   70,  198,   71,  197,  196,   72,   73,
       74,   75,   97,   98,   99,  100,  195,  101,  102,  194,
      103,  193,  104,  105,  106,  107,  192,  191,  108,  109,
      110,  121,  122,  123,  124,  190,  125,  126,  189,  127,
      186,  128,  129,  185,  130,  184,  131,  132,  133,  134,
      148,  149,  150,  183,  182,  151,  181,  180,  152,  177,
      169,  168,  167,  166,  165,  153,  154,  164,  156,  147,
      144,  155,  157,  158,  159,  143,  140,  160,  139,  138,

      161,  137,  136,  135,  118,  117,  116,  115,  162,  112,
      111,   96,   93,  163,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   42,   42,

       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   52,   52,   52,   52,   52,   91,   52,  540,
      540,   52,   76,   76,  540,   76,   76,  540,   76,  540,

      540,   76,   77,   77,  540,   77,   77,  540,   77,  540,
      540,   77,   78,  540,  540,  540,  540,  540,   78,  540,
       78,   78,   79,  540,  540,  540,  540,  540,   79,  540,
       79,   79,   80,  540,  540,   80,   80,  540,   80,   80,
       80,   80,   81,  540,  540,  540,  540,  540,   81,  540,
       81,   81,   82,  540,  540,  540,  540,  540,   82,  540,
       82,   82,   83,  540,  540,  540,  540,  540,   83,   86,
       86,  540,   86,   86,  540,   86,  540,  540,   86,   92,
       92,   92,   92,   92,   92,  540,   92,  540,  540,   92,
      345,  345,  540,  345,  345,  345,  345,  540,  540,  345,

      346,  540,  540,  540,  346,  346,  540,  540,  540,  346,
       29,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540
    } ;

static yyconst flex_int16_t yy_chk[1150] =
    {   0,
        1,    1,    1,    1,  565,  564,  539,  538,    1,  537,
        1,   58,   71,   48,   97,   47,  536,   53,   63,   58,
       71,   74,    0,   97,   98,  109,   98,   74,  535,   47,
       48,   53,   63,  121,    1,    1,    2,    2,    2,    2,
      109,   99,  121,  101,    2,   99,    2,  101,   99,  122,
      123,  122,  125,  133,  123,  152,  125,  123,  161,  534,
      152,  533,  140,  161,  532,  188,  531,  218,  133,  530,
        2,    2,    3,    3,    3,  140,  188,    3,  218,  239,
        3,  249,    3,  239,  253,  249,  253,  366,  253,  253,
      345,  529,  345,  528,  345,  345,  392,  527,  526,  525,

      524,  523,  366,  522,  521,  520,    3,    3,    4,    4,
        4,  392,  519,    4,  518,  517,    4,  516,    4,  515,
      514,  513,  512,  511,  510,  509,  508,  507,  506,  505,
      504,  503,  502,  501,  500,  499,  498,  497,  496,  495,
      494,  493,    4,    4,    5,    5,    5,  492,  491,    5,
      490,  489,    5,  488,    5,  487,  486,  485,  484,  483,
      482,  481,  480,  479,  478,  477,  476,  475,  474,  473,
      472,  471,  470,  469,  468,  467,  466,  465,    5,    5,
        6,    6,    6,  464,  463,    6,  462,  461,    6,  460,
        6,  459,  458,  457,  456,  455,  454,  453,  452,  451,

      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  439,  438,  437,    6,    6,    7,    7,    7,  436,
        7,    7,    7,    7,    7,  435,    7,    8,    8,    8,
      434,    8,    8,    8,    8,    8,  433,    8,    9,    9,
        9,  432,    9,    9,    9,    9,    9,  431,    9,   10,
       10,   10,  430,   10,   10,   10,   10,   10,  429,   10,
       11,   11,   11,  428,   11,   11,  427,  426,   11,   12,
       12,   12,  425,   12,   12,  424,  423,   12,   13,   13,
       13,  422,   13,   13,   13,   13,   13,  421,   13,   14,
       14,   14,  420,   14,   14,   14,   14,   14,  419,   14,

       15,   15,   15,  418,   15,   15,   15,   15,   15,  417,
       15,   16,   16,   16,  416,   16,   16,   16,   16,   16,
      415,   16,   17,   17,   17,  414,   17,   17,   17,   17,
       17,  413,   17,  412,  411,  410,  409,  408,  407,  406,
      405,  404,  403,  402,  401,  400,  399,  398,  397,  396,
      395,  394,  393,  391,  390,  389,   17,   17,   17,   18,
       18,   18,  388,   18,   18,   18,   18,   18,  387,   18,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      365,  364,  363,   18,   18,   18,   19,   19,   19,  362,

       19,   19,   19,   19,   19,   19,   19,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  344,  343,  342,  341,  340,  339,  338,  337,
       19,   19,   19,   20,   20,   20,  336,   20,   20,   20,
       20,   20,   20,   20,  335,  334,  333,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,   20,   20,   20,
       21,   21,   21,  312,   21,   21,   21,   21,   21,   21,
       21,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,

      292,  291,  290,  289,   21,   21,   21,   22,   22,   22,
      288,   22,   22,   22,   22,   22,   22,   22,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,   22,   22,   22,   23,   23,   23,  264,  263,   23,
      262,  261,   23,  260,   23,  259,  258,  257,  256,  255,
      254,  252,  251,  250,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  238,  237,  236,  235,  234,   23,   23,
      233,   23,   24,   24,   24,  232,  231,   24,  230,  229,
       24,  228,   24,  227,  226,  225,  224,  223,  222,  221,

      220,  219,  217,  216,  215,  214,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  204,   24,   24,  203,   24,
       27,   27,  202,  201,  200,  199,  198,  197,   27,  196,
       27,  195,  194,  193,  192,  191,  190,  189,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,   27,   27,   28,   28,  171,  170,
      169,  168,  167,  166,   28,  165,   28,  164,  163,  162,
      160,  159,  158,  157,  156,  155,  154,  153,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  139,
       28,   28,   34,  138,  137,   34,   34,  136,  135,  134,

       34,  132,   34,  131,  130,   34,  129,  128,   34,   34,
       34,   34,   35,   35,   35,   35,   35,  127,  126,  124,
       35,  120,   35,   35,  119,   35,  118,  117,   35,   35,
       35,   35,   55,   55,   55,   55,  116,   55,   55,  115,
       55,  114,   55,   55,   55,   55,  113,  112,   55,   55,
       55,   64,   64,   64,   64,  111,   64,   64,  110,   64,
      108,   64,   64,  107,   64,  106,   64,   64,   64,   64,
       87,   87,   87,  105,  104,   87,  103,  102,   87,  100,
       96,   95,   94,   93,   91,   87,   87,   90,   88,   75,
       73,   87,   89,   89,   89,   72,   70,   89,   69,   68,

       89,   67,   66,   65,   62,   61,   60,   59,   89,   57,
       56,   54,   51,   89,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      544,  544,  544,  544,  544,  544,  544,  544,  544,  544,
      544,  544,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547,  547,  547,  548,  548,

      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      554,  554,  554,  554,  554,  554,  554,  554,  554,  554,
      554,  554,  555,  555,  555,  555,  555,   49,  555,   29,
        0,  555,  556,  556,    0,  556,  556,    0,  556,    0,

        0,  556,  557,  557,    0,  557,  557,    0,  557,    0,
        0,  557,  558,    0,    0,    0,    0,    0,  558,    0,
      558,  558,  559,    0,    0,    0,    0,    0,  559,    0,
      559,  559,  560,    0,    0,  560,  560,    0,  560,  560,
      560,  560,  561,    0,    0,    0,    0,    0,  561,    0,
      561,  561,  562,    0,    0,    0,    0,    0,  562,    0,
      562,  562,  563,    0,    0,    0,    0,    0,  563,  566,
      566,    0,  566,  566,    0,  566,    0,    0,  566,  567,
      567,  567,  567,  567,  567,    0,  567,    0,    0,  567,
      568,  568,    0,  568,  568,  568,  568,    0,    0,  568,

      569,    0,    0,    0,  569,  569,    0,    0,    0,  569,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[110] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "report.l"
#line 2 "report.l"
#include "report2007.h"
#include "y.tab.h"
#include <string.h>
#include <stdlib.h>

#line 913 "lex.yy.c"

#define INITIAL 0
#define title 1
#define subtitle 2
#define name 3
#define ident 4
#define email 5
#define url 6
#define aff 7
#define date 8
#define inst 9
#define key 10
#define para 11
#define akn 12
#define code 13

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 10 "report.l"


#line 1111 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 541 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1111 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 12 "report.l"
{return BREPORT;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 13 "report.l"
{return EREPORT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 14 "report.l"
{return BFM;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 15 "report.l"
{return TOC;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 16 "report.l"
{return LOF;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 17 "report.l"
{return LOT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 18 "report.l"
{return EFM;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 19 "report.l"
{BEGIN title; return BTITLE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 20 "report.l"
{return ETITLE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 21 "report.l"
{BEGIN subtitle; return BSUBTITLE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 22 "report.l"
{return ESUBTITLE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 23 "report.l"
{BEGIN 0;yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 24 "report.l"
{BEGIN 0;yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 25 "report.l"
{return BAUTHOR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 26 "report.l"
{return EAUTHOR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 27 "report.l"
{BEGIN name;return BNAME;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 28 "report.l"
{return ENAME;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 29 "report.l"
{BEGIN 0;yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 30 "report.l"
{BEGIN ident;return BIDENT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 31 "report.l"
{return EINDENT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 32 "report.l"
{BEGIN 0; yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 33 "report.l"
{BEGIN email;return BMAIL;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 34 "report.l"
{return EMAIL;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 35 "report.l"
{BEGIN 0; yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 36 "report.l"
{BEGIN url;return BURL;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 37 "report.l"
{return EURL;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 38 "report.l"
{BEGIN 0; yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 39 "report.l"
{BEGIN aff; return BAFF;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 40 "report.l"
{return EAFF;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 41 "report.l"
{BEGIN 0; yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 42 "report.l"
{BEGIN date; return BDATE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 43 "report.l"
{return EDATE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 44 "report.l"
{BEGIN 0;yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 45 "report.l"
{BEGIN inst; return BINST;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 46 "report.l"
{return EINST;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 47 "report.l"
{BEGIN 0; yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 48 "report.l"
{return BKEYS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 49 "report.l"
{return EKEYS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 50 "report.l"
{BEGIN key;return BKEY;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 51 "report.l"
{return EKEY;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 52 "report.l"
{BEGIN 0;yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 53 "report.l"
{return BABS;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 54 "report.l"
{return EABS;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 55 "report.l"
{BEGIN para;return BPARA;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 56 "report.l"
{BEGIN 0;return EPARA;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 57 "report.l"
{yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 58 "report.l"
{yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 59 "report.l"
{return BFOOT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 60 "report.l"
{return EFOOT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 61 "report.l"
{return BREF;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 62 "report.l"
{return EREF;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 63 "report.l"
{return BXREF;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 64 "report.l"
{return EXREF;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 65 "report.l"
{return BCIT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 66 "report.l"
{return ECIT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 67 "report.l"
{return BITERM;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 68 "report.l"
{return EITERM;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 69 "report.l"
{return BBLOD;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 70 "report.l"
{return EBOLD;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 71 "report.l"
{return BACRONYM;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 72 "report.l"
{return EACRONYM;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 73 "report.l"
{return BTITLE;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 74 "report.l"
{return ETITLE;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 75 "report.l"
{return BITALIC;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 76 "report.l"
{return EITALIC;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 77 "report.l"
{return BINLINE;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 78 "report.l"
{return EINLINE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 79 "report.l"
{return BAKN;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 80 "report.l"
{return EAKN;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 81 "report.l"
{return BBODY;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 82 "report.l"
{return EBODY;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 83 "report.l"
{return BCHAP;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 84 "report.l"
{return ECHAP;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 85 "report.l"
{return BSEC;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 86 "report.l"
{return ESEC;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 87 "report.l"
{return BSUBSEC;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 88 "report.l"
{return ESUBSEC;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 89 "report.l"
{return BSUBSUBSECTION;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 90 "report.l"
{return ESUBSUBSECTION;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 91 "report.l"
{return BLIST;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 92 "report.l"
{return ELIST;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 93 "report.l"
{return BDESC;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 94 "report.l"
{return EDESC;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 95 "report.l"
{return BITEM;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 96 "report.l"
{return EITEM;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 97 "report.l"
{return BNUM;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 98 "report.l"
{return ENUM;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 99 "report.l"
{BEGIN code;return BCODE;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 100 "report.l"
{BEGIN 0;return ECODE;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 101 "report.l"
{return BSUM;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 102 "report.l"
{return ESUM;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 103 "report.l"
{return BFIG;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 104 "report.l"
{return EFIG;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 105 "report.l"
{return BGRAPH;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 106 "report.l"
{return EGRAPH;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 107 "report.l"
{return BCAPTION;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 108 "report.l"
{return ECAPTION;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 109 "report.l"
{return BTABLE;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 110 "report.l"
{return ETABLE;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 111 "report.l"
{return BROW;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 112 "report.l"
{return EROW;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 113 "report.l"
{return BCELL;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 114 "report.l"
{return ECELL;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 115 "report.l"
{return BBM;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 116 "report.l"
{return EBM;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 117 "report.l"
{yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 118 "report.l"
{yylval.str=strdup(yytext);return TEXTO;}
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 119 "report.l"
;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 120 "report.l"
ECHO;
	YY_BREAK
#line 1751 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(title):
case YY_STATE_EOF(subtitle):
case YY_STATE_EOF(name):
case YY_STATE_EOF(ident):
case YY_STATE_EOF(email):
case YY_STATE_EOF(url):
case YY_STATE_EOF(aff):
case YY_STATE_EOF(date):
case YY_STATE_EOF(inst):
case YY_STATE_EOF(key):
case YY_STATE_EOF(para):
case YY_STATE_EOF(akn):
case YY_STATE_EOF(code):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 541 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 541 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 540);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 120 "report.l"
